# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ptprashanttripathi
open_collective: ptprashanttripathi
ko_fi: ptprashanttripathi
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["UPI", “https://ptprashanttripathi.github.io/linkpe/?pa=pt1998@ybl&pn=Pt.+Prashant+Tripathi”]